// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.2
// source: network.proto

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetworkModule_Name_FullMethodName                   = "/network.NetworkModule/Name"
	NetworkModule_DisplayName_FullMethodName            = "/network.NetworkModule/DisplayName"
	NetworkModule_Version_FullMethodName                = "/network.NetworkModule/Version"
	NetworkModule_BinaryName_FullMethodName             = "/network.NetworkModule/BinaryName"
	NetworkModule_BinarySource_FullMethodName           = "/network.NetworkModule/BinarySource"
	NetworkModule_DefaultBinaryVersion_FullMethodName   = "/network.NetworkModule/DefaultBinaryVersion"
	NetworkModule_DefaultChainID_FullMethodName         = "/network.NetworkModule/DefaultChainID"
	NetworkModule_Bech32Prefix_FullMethodName           = "/network.NetworkModule/Bech32Prefix"
	NetworkModule_BaseDenom_FullMethodName              = "/network.NetworkModule/BaseDenom"
	NetworkModule_GenesisConfig_FullMethodName          = "/network.NetworkModule/GenesisConfig"
	NetworkModule_DefaultPorts_FullMethodName           = "/network.NetworkModule/DefaultPorts"
	NetworkModule_DefaultGeneratorConfig_FullMethodName = "/network.NetworkModule/DefaultGeneratorConfig"
	NetworkModule_DockerImage_FullMethodName            = "/network.NetworkModule/DockerImage"
	NetworkModule_DockerImageTag_FullMethodName         = "/network.NetworkModule/DockerImageTag"
	NetworkModule_DockerHomeDir_FullMethodName          = "/network.NetworkModule/DockerHomeDir"
	NetworkModule_InitCommand_FullMethodName            = "/network.NetworkModule/InitCommand"
	NetworkModule_StartCommand_FullMethodName           = "/network.NetworkModule/StartCommand"
	NetworkModule_ExportCommand_FullMethodName          = "/network.NetworkModule/ExportCommand"
	NetworkModule_DefaultNodeHome_FullMethodName        = "/network.NetworkModule/DefaultNodeHome"
	NetworkModule_PIDFileName_FullMethodName            = "/network.NetworkModule/PIDFileName"
	NetworkModule_LogFileName_FullMethodName            = "/network.NetworkModule/LogFileName"
	NetworkModule_ProcessPattern_FullMethodName         = "/network.NetworkModule/ProcessPattern"
	NetworkModule_ModifyGenesis_FullMethodName          = "/network.NetworkModule/ModifyGenesis"
	NetworkModule_GenerateDevnet_FullMethodName         = "/network.NetworkModule/GenerateDevnet"
	NetworkModule_GetCodec_FullMethodName               = "/network.NetworkModule/GetCodec"
	NetworkModule_Validate_FullMethodName               = "/network.NetworkModule/Validate"
)

// NetworkModuleClient is the client API for NetworkModule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NetworkModule service definition
type NetworkModuleClient interface {
	// Identity
	Name(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error)
	DisplayName(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error)
	Version(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error)
	// Binary
	BinaryName(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error)
	BinarySource(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BinarySourceResponse, error)
	DefaultBinaryVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error)
	// Chain
	DefaultChainID(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error)
	Bech32Prefix(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error)
	BaseDenom(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error)
	// Configuration
	GenesisConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GenesisConfigResponse, error)
	DefaultPorts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PortConfigResponse, error)
	DefaultGeneratorConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GeneratorConfigResponse, error)
	// Docker
	DockerImage(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error)
	DockerImageTag(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*StringResponse, error)
	DockerHomeDir(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error)
	// Commands
	InitCommand(ctx context.Context, in *InitCommandRequest, opts ...grpc.CallOption) (*StringListResponse, error)
	StartCommand(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*StringListResponse, error)
	ExportCommand(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*StringListResponse, error)
	// Paths
	DefaultNodeHome(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error)
	PIDFileName(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error)
	LogFileName(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error)
	ProcessPattern(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error)
	// Operations
	ModifyGenesis(ctx context.Context, in *ModifyGenesisRequest, opts ...grpc.CallOption) (*BytesResponse, error)
	GenerateDevnet(ctx context.Context, in *GenerateDevnetRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
	GetCodec(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BytesResponse, error)
	// Validation
	Validate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ErrorResponse, error)
}

type networkModuleClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkModuleClient(cc grpc.ClientConnInterface) NetworkModuleClient {
	return &networkModuleClient{cc}
}

func (c *networkModuleClient) Name(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, NetworkModule_Name_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) DisplayName(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, NetworkModule_DisplayName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) Version(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, NetworkModule_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) BinaryName(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, NetworkModule_BinaryName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) BinarySource(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BinarySourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BinarySourceResponse)
	err := c.cc.Invoke(ctx, NetworkModule_BinarySource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) DefaultBinaryVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, NetworkModule_DefaultBinaryVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) DefaultChainID(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, NetworkModule_DefaultChainID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) Bech32Prefix(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, NetworkModule_Bech32Prefix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) BaseDenom(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, NetworkModule_BaseDenom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) GenesisConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GenesisConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenesisConfigResponse)
	err := c.cc.Invoke(ctx, NetworkModule_GenesisConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) DefaultPorts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PortConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortConfigResponse)
	err := c.cc.Invoke(ctx, NetworkModule_DefaultPorts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) DefaultGeneratorConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GeneratorConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneratorConfigResponse)
	err := c.cc.Invoke(ctx, NetworkModule_DefaultGeneratorConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) DockerImage(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, NetworkModule_DockerImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) DockerImageTag(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*StringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, NetworkModule_DockerImageTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) DockerHomeDir(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, NetworkModule_DockerHomeDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) InitCommand(ctx context.Context, in *InitCommandRequest, opts ...grpc.CallOption) (*StringListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringListResponse)
	err := c.cc.Invoke(ctx, NetworkModule_InitCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) StartCommand(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*StringListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringListResponse)
	err := c.cc.Invoke(ctx, NetworkModule_StartCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) ExportCommand(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*StringListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringListResponse)
	err := c.cc.Invoke(ctx, NetworkModule_ExportCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) DefaultNodeHome(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, NetworkModule_DefaultNodeHome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) PIDFileName(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, NetworkModule_PIDFileName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) LogFileName(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, NetworkModule_LogFileName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) ProcessPattern(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, NetworkModule_ProcessPattern_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) ModifyGenesis(ctx context.Context, in *ModifyGenesisRequest, opts ...grpc.CallOption) (*BytesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BytesResponse)
	err := c.cc.Invoke(ctx, NetworkModule_ModifyGenesis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) GenerateDevnet(ctx context.Context, in *GenerateDevnetRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, NetworkModule_GenerateDevnet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) GetCodec(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BytesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BytesResponse)
	err := c.cc.Invoke(ctx, NetworkModule_GetCodec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkModuleClient) Validate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ErrorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, NetworkModule_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkModuleServer is the server API for NetworkModule service.
// All implementations must embed UnimplementedNetworkModuleServer
// for forward compatibility.
//
// NetworkModule service definition
type NetworkModuleServer interface {
	// Identity
	Name(context.Context, *Empty) (*StringResponse, error)
	DisplayName(context.Context, *Empty) (*StringResponse, error)
	Version(context.Context, *Empty) (*StringResponse, error)
	// Binary
	BinaryName(context.Context, *Empty) (*StringResponse, error)
	BinarySource(context.Context, *Empty) (*BinarySourceResponse, error)
	DefaultBinaryVersion(context.Context, *Empty) (*StringResponse, error)
	// Chain
	DefaultChainID(context.Context, *Empty) (*StringResponse, error)
	Bech32Prefix(context.Context, *Empty) (*StringResponse, error)
	BaseDenom(context.Context, *Empty) (*StringResponse, error)
	// Configuration
	GenesisConfig(context.Context, *Empty) (*GenesisConfigResponse, error)
	DefaultPorts(context.Context, *Empty) (*PortConfigResponse, error)
	DefaultGeneratorConfig(context.Context, *Empty) (*GeneratorConfigResponse, error)
	// Docker
	DockerImage(context.Context, *Empty) (*StringResponse, error)
	DockerImageTag(context.Context, *StringRequest) (*StringResponse, error)
	DockerHomeDir(context.Context, *Empty) (*StringResponse, error)
	// Commands
	InitCommand(context.Context, *InitCommandRequest) (*StringListResponse, error)
	StartCommand(context.Context, *StringRequest) (*StringListResponse, error)
	ExportCommand(context.Context, *StringRequest) (*StringListResponse, error)
	// Paths
	DefaultNodeHome(context.Context, *Empty) (*StringResponse, error)
	PIDFileName(context.Context, *Empty) (*StringResponse, error)
	LogFileName(context.Context, *Empty) (*StringResponse, error)
	ProcessPattern(context.Context, *Empty) (*StringResponse, error)
	// Operations
	ModifyGenesis(context.Context, *ModifyGenesisRequest) (*BytesResponse, error)
	GenerateDevnet(context.Context, *GenerateDevnetRequest) (*ErrorResponse, error)
	GetCodec(context.Context, *Empty) (*BytesResponse, error)
	// Validation
	Validate(context.Context, *Empty) (*ErrorResponse, error)
	mustEmbedUnimplementedNetworkModuleServer()
}

// UnimplementedNetworkModuleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkModuleServer struct{}

func (UnimplementedNetworkModuleServer) Name(context.Context, *Empty) (*StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Name not implemented")
}
func (UnimplementedNetworkModuleServer) DisplayName(context.Context, *Empty) (*StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisplayName not implemented")
}
func (UnimplementedNetworkModuleServer) Version(context.Context, *Empty) (*StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedNetworkModuleServer) BinaryName(context.Context, *Empty) (*StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BinaryName not implemented")
}
func (UnimplementedNetworkModuleServer) BinarySource(context.Context, *Empty) (*BinarySourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BinarySource not implemented")
}
func (UnimplementedNetworkModuleServer) DefaultBinaryVersion(context.Context, *Empty) (*StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DefaultBinaryVersion not implemented")
}
func (UnimplementedNetworkModuleServer) DefaultChainID(context.Context, *Empty) (*StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DefaultChainID not implemented")
}
func (UnimplementedNetworkModuleServer) Bech32Prefix(context.Context, *Empty) (*StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bech32Prefix not implemented")
}
func (UnimplementedNetworkModuleServer) BaseDenom(context.Context, *Empty) (*StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BaseDenom not implemented")
}
func (UnimplementedNetworkModuleServer) GenesisConfig(context.Context, *Empty) (*GenesisConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenesisConfig not implemented")
}
func (UnimplementedNetworkModuleServer) DefaultPorts(context.Context, *Empty) (*PortConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DefaultPorts not implemented")
}
func (UnimplementedNetworkModuleServer) DefaultGeneratorConfig(context.Context, *Empty) (*GeneratorConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DefaultGeneratorConfig not implemented")
}
func (UnimplementedNetworkModuleServer) DockerImage(context.Context, *Empty) (*StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DockerImage not implemented")
}
func (UnimplementedNetworkModuleServer) DockerImageTag(context.Context, *StringRequest) (*StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DockerImageTag not implemented")
}
func (UnimplementedNetworkModuleServer) DockerHomeDir(context.Context, *Empty) (*StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DockerHomeDir not implemented")
}
func (UnimplementedNetworkModuleServer) InitCommand(context.Context, *InitCommandRequest) (*StringListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitCommand not implemented")
}
func (UnimplementedNetworkModuleServer) StartCommand(context.Context, *StringRequest) (*StringListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartCommand not implemented")
}
func (UnimplementedNetworkModuleServer) ExportCommand(context.Context, *StringRequest) (*StringListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportCommand not implemented")
}
func (UnimplementedNetworkModuleServer) DefaultNodeHome(context.Context, *Empty) (*StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DefaultNodeHome not implemented")
}
func (UnimplementedNetworkModuleServer) PIDFileName(context.Context, *Empty) (*StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PIDFileName not implemented")
}
func (UnimplementedNetworkModuleServer) LogFileName(context.Context, *Empty) (*StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogFileName not implemented")
}
func (UnimplementedNetworkModuleServer) ProcessPattern(context.Context, *Empty) (*StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessPattern not implemented")
}
func (UnimplementedNetworkModuleServer) ModifyGenesis(context.Context, *ModifyGenesisRequest) (*BytesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyGenesis not implemented")
}
func (UnimplementedNetworkModuleServer) GenerateDevnet(context.Context, *GenerateDevnetRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateDevnet not implemented")
}
func (UnimplementedNetworkModuleServer) GetCodec(context.Context, *Empty) (*BytesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCodec not implemented")
}
func (UnimplementedNetworkModuleServer) Validate(context.Context, *Empty) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedNetworkModuleServer) mustEmbedUnimplementedNetworkModuleServer() {}
func (UnimplementedNetworkModuleServer) testEmbeddedByValue()                       {}

// UnsafeNetworkModuleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkModuleServer will
// result in compilation errors.
type UnsafeNetworkModuleServer interface {
	mustEmbedUnimplementedNetworkModuleServer()
}

func RegisterNetworkModuleServer(s grpc.ServiceRegistrar, srv NetworkModuleServer) {
	// If the following call pancis, it indicates UnimplementedNetworkModuleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetworkModule_ServiceDesc, srv)
}

func _NetworkModule_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_Name_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).Name(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_DisplayName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).DisplayName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_DisplayName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).DisplayName(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).Version(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_BinaryName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).BinaryName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_BinaryName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).BinaryName(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_BinarySource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).BinarySource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_BinarySource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).BinarySource(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_DefaultBinaryVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).DefaultBinaryVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_DefaultBinaryVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).DefaultBinaryVersion(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_DefaultChainID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).DefaultChainID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_DefaultChainID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).DefaultChainID(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_Bech32Prefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).Bech32Prefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_Bech32Prefix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).Bech32Prefix(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_BaseDenom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).BaseDenom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_BaseDenom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).BaseDenom(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_GenesisConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).GenesisConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_GenesisConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).GenesisConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_DefaultPorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).DefaultPorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_DefaultPorts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).DefaultPorts(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_DefaultGeneratorConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).DefaultGeneratorConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_DefaultGeneratorConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).DefaultGeneratorConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_DockerImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).DockerImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_DockerImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).DockerImage(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_DockerImageTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).DockerImageTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_DockerImageTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).DockerImageTag(ctx, req.(*StringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_DockerHomeDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).DockerHomeDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_DockerHomeDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).DockerHomeDir(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_InitCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).InitCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_InitCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).InitCommand(ctx, req.(*InitCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_StartCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).StartCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_StartCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).StartCommand(ctx, req.(*StringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_ExportCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).ExportCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_ExportCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).ExportCommand(ctx, req.(*StringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_DefaultNodeHome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).DefaultNodeHome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_DefaultNodeHome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).DefaultNodeHome(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_PIDFileName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).PIDFileName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_PIDFileName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).PIDFileName(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_LogFileName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).LogFileName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_LogFileName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).LogFileName(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_ProcessPattern_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).ProcessPattern(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_ProcessPattern_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).ProcessPattern(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_ModifyGenesis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyGenesisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).ModifyGenesis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_ModifyGenesis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).ModifyGenesis(ctx, req.(*ModifyGenesisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_GenerateDevnet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDevnetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).GenerateDevnet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_GenerateDevnet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).GenerateDevnet(ctx, req.(*GenerateDevnetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_GetCodec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).GetCodec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_GetCodec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).GetCodec(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkModule_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkModuleServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkModule_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkModuleServer).Validate(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// NetworkModule_ServiceDesc is the grpc.ServiceDesc for NetworkModule service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkModule_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "network.NetworkModule",
	HandlerType: (*NetworkModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Name",
			Handler:    _NetworkModule_Name_Handler,
		},
		{
			MethodName: "DisplayName",
			Handler:    _NetworkModule_DisplayName_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _NetworkModule_Version_Handler,
		},
		{
			MethodName: "BinaryName",
			Handler:    _NetworkModule_BinaryName_Handler,
		},
		{
			MethodName: "BinarySource",
			Handler:    _NetworkModule_BinarySource_Handler,
		},
		{
			MethodName: "DefaultBinaryVersion",
			Handler:    _NetworkModule_DefaultBinaryVersion_Handler,
		},
		{
			MethodName: "DefaultChainID",
			Handler:    _NetworkModule_DefaultChainID_Handler,
		},
		{
			MethodName: "Bech32Prefix",
			Handler:    _NetworkModule_Bech32Prefix_Handler,
		},
		{
			MethodName: "BaseDenom",
			Handler:    _NetworkModule_BaseDenom_Handler,
		},
		{
			MethodName: "GenesisConfig",
			Handler:    _NetworkModule_GenesisConfig_Handler,
		},
		{
			MethodName: "DefaultPorts",
			Handler:    _NetworkModule_DefaultPorts_Handler,
		},
		{
			MethodName: "DefaultGeneratorConfig",
			Handler:    _NetworkModule_DefaultGeneratorConfig_Handler,
		},
		{
			MethodName: "DockerImage",
			Handler:    _NetworkModule_DockerImage_Handler,
		},
		{
			MethodName: "DockerImageTag",
			Handler:    _NetworkModule_DockerImageTag_Handler,
		},
		{
			MethodName: "DockerHomeDir",
			Handler:    _NetworkModule_DockerHomeDir_Handler,
		},
		{
			MethodName: "InitCommand",
			Handler:    _NetworkModule_InitCommand_Handler,
		},
		{
			MethodName: "StartCommand",
			Handler:    _NetworkModule_StartCommand_Handler,
		},
		{
			MethodName: "ExportCommand",
			Handler:    _NetworkModule_ExportCommand_Handler,
		},
		{
			MethodName: "DefaultNodeHome",
			Handler:    _NetworkModule_DefaultNodeHome_Handler,
		},
		{
			MethodName: "PIDFileName",
			Handler:    _NetworkModule_PIDFileName_Handler,
		},
		{
			MethodName: "LogFileName",
			Handler:    _NetworkModule_LogFileName_Handler,
		},
		{
			MethodName: "ProcessPattern",
			Handler:    _NetworkModule_ProcessPattern_Handler,
		},
		{
			MethodName: "ModifyGenesis",
			Handler:    _NetworkModule_ModifyGenesis_Handler,
		},
		{
			MethodName: "GenerateDevnet",
			Handler:    _NetworkModule_GenerateDevnet_Handler,
		},
		{
			MethodName: "GetCodec",
			Handler:    _NetworkModule_GetCodec_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _NetworkModule_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "network.proto",
}
