version: "2"
run:
  modules-download-mode: readonly
linters:
  # Only enable linters that pass with current codebase
  # Additional linters can be enabled incrementally
  enable:
    - gocritic
    - gosec
    - misspell
  disable:
    - unused       # TODO: Enable after cleanup
    - ineffassign  # TODO: Enable after cleanup
    - staticcheck  # TODO: Enable after cleanup
  settings:
    gocritic:
      disabled-checks:
        - hugeParam
        - commentedOutCode
        - stringXbytes
        - ifElseChain
        - sprintfQuotedString
        - commentFormatting
      enabled-tags:
        - diagnostic
        - performance
    gosec:
      excludes:
        - G104  # Audit errors not checked
        - G204  # Subprocess launched with variable
        - G306  # WriteFile permissions
        - G115  # Integer overflow conversion
      config:
        G301: "0750"
        G302: "0600"
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gocritic
          - gosec
        path: _test\.go
      - linters:
          - errcheck
          - gosec
        path: testutil/
      - linters:
          - errcheck
          - gosec
        path: mocks/
      # Exclude errcheck for known intentional ignores
      - linters:
          - errcheck
        text: "Error return value of .*(Run|Wait|Signal|Cleanup|MarkFlagRequired|Save|Sscanf).* is not checked"
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 3
  new: false
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
