# GoReleaser configuration for stable-devnet
# https://goreleaser.com/customization/

version: 2

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: devnet-builder
    main: ./cmd/devnet-builder
    binary: devnet-builder
    env:
      - CGO_ENABLED=0
      - GOPRIVATE=github.com/stablelabs/*
      - GOSUMDB=off
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.GitCommit={{.Commit}}
      - -X main.BuildDate={{.Date}}

archives:
  - id: devnet-builder-archive
    ids:
      - devnet-builder
    name_template: >-
      devnet-builder_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    formats:
      - tar.gz
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: git
  abbrev: 0
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - '^Merge pull request'
      - '^Merge branch'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Security
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Performance
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Dependencies
      regexp: '^.*?deps(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: Other
      order: 999

release:
  github:
    owner: stablelabs
    name: stable-devnet
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Devnet Builder {{ .Tag }}

    Release of devnet-builder version {{ .Version }}.

  footer: |
    ---
    **Full Changelog**: https://github.com/{{ .Env.GITHUB_REPOSITORY }}/compare/{{ .PreviousTag }}...{{ .Tag }}

  name_template: "{{ .Tag }}"
