// api/proto/v1/devnet.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.27.2
// source: devnet.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DevnetService_CreateDevnet_FullMethodName = "/devnetd.v1.DevnetService/CreateDevnet"
	DevnetService_GetDevnet_FullMethodName    = "/devnetd.v1.DevnetService/GetDevnet"
	DevnetService_ListDevnets_FullMethodName  = "/devnetd.v1.DevnetService/ListDevnets"
	DevnetService_DeleteDevnet_FullMethodName = "/devnetd.v1.DevnetService/DeleteDevnet"
	DevnetService_StartDevnet_FullMethodName  = "/devnetd.v1.DevnetService/StartDevnet"
	DevnetService_StopDevnet_FullMethodName   = "/devnetd.v1.DevnetService/StopDevnet"
)

// DevnetServiceClient is the client API for DevnetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DevnetServiceClient interface {
	CreateDevnet(ctx context.Context, in *CreateDevnetRequest, opts ...grpc.CallOption) (*Devnet, error)
	GetDevnet(ctx context.Context, in *GetDevnetRequest, opts ...grpc.CallOption) (*Devnet, error)
	ListDevnets(ctx context.Context, in *ListDevnetsRequest, opts ...grpc.CallOption) (*ListDevnetsResponse, error)
	DeleteDevnet(ctx context.Context, in *DeleteDevnetRequest, opts ...grpc.CallOption) (*DeleteDevnetResponse, error)
	StartDevnet(ctx context.Context, in *StartDevnetRequest, opts ...grpc.CallOption) (*Devnet, error)
	StopDevnet(ctx context.Context, in *StopDevnetRequest, opts ...grpc.CallOption) (*Devnet, error)
}

type devnetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDevnetServiceClient(cc grpc.ClientConnInterface) DevnetServiceClient {
	return &devnetServiceClient{cc}
}

func (c *devnetServiceClient) CreateDevnet(ctx context.Context, in *CreateDevnetRequest, opts ...grpc.CallOption) (*Devnet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Devnet)
	err := c.cc.Invoke(ctx, DevnetService_CreateDevnet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devnetServiceClient) GetDevnet(ctx context.Context, in *GetDevnetRequest, opts ...grpc.CallOption) (*Devnet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Devnet)
	err := c.cc.Invoke(ctx, DevnetService_GetDevnet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devnetServiceClient) ListDevnets(ctx context.Context, in *ListDevnetsRequest, opts ...grpc.CallOption) (*ListDevnetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevnetsResponse)
	err := c.cc.Invoke(ctx, DevnetService_ListDevnets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devnetServiceClient) DeleteDevnet(ctx context.Context, in *DeleteDevnetRequest, opts ...grpc.CallOption) (*DeleteDevnetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDevnetResponse)
	err := c.cc.Invoke(ctx, DevnetService_DeleteDevnet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devnetServiceClient) StartDevnet(ctx context.Context, in *StartDevnetRequest, opts ...grpc.CallOption) (*Devnet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Devnet)
	err := c.cc.Invoke(ctx, DevnetService_StartDevnet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devnetServiceClient) StopDevnet(ctx context.Context, in *StopDevnetRequest, opts ...grpc.CallOption) (*Devnet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Devnet)
	err := c.cc.Invoke(ctx, DevnetService_StopDevnet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DevnetServiceServer is the server API for DevnetService service.
// All implementations must embed UnimplementedDevnetServiceServer
// for forward compatibility.
type DevnetServiceServer interface {
	CreateDevnet(context.Context, *CreateDevnetRequest) (*Devnet, error)
	GetDevnet(context.Context, *GetDevnetRequest) (*Devnet, error)
	ListDevnets(context.Context, *ListDevnetsRequest) (*ListDevnetsResponse, error)
	DeleteDevnet(context.Context, *DeleteDevnetRequest) (*DeleteDevnetResponse, error)
	StartDevnet(context.Context, *StartDevnetRequest) (*Devnet, error)
	StopDevnet(context.Context, *StopDevnetRequest) (*Devnet, error)
	mustEmbedUnimplementedDevnetServiceServer()
}

// UnimplementedDevnetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDevnetServiceServer struct{}

func (UnimplementedDevnetServiceServer) CreateDevnet(context.Context, *CreateDevnetRequest) (*Devnet, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDevnet not implemented")
}
func (UnimplementedDevnetServiceServer) GetDevnet(context.Context, *GetDevnetRequest) (*Devnet, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDevnet not implemented")
}
func (UnimplementedDevnetServiceServer) ListDevnets(context.Context, *ListDevnetsRequest) (*ListDevnetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevnets not implemented")
}
func (UnimplementedDevnetServiceServer) DeleteDevnet(context.Context, *DeleteDevnetRequest) (*DeleteDevnetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDevnet not implemented")
}
func (UnimplementedDevnetServiceServer) StartDevnet(context.Context, *StartDevnetRequest) (*Devnet, error) {
	return nil, status.Error(codes.Unimplemented, "method StartDevnet not implemented")
}
func (UnimplementedDevnetServiceServer) StopDevnet(context.Context, *StopDevnetRequest) (*Devnet, error) {
	return nil, status.Error(codes.Unimplemented, "method StopDevnet not implemented")
}
func (UnimplementedDevnetServiceServer) mustEmbedUnimplementedDevnetServiceServer() {}
func (UnimplementedDevnetServiceServer) testEmbeddedByValue()                       {}

// UnsafeDevnetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DevnetServiceServer will
// result in compilation errors.
type UnsafeDevnetServiceServer interface {
	mustEmbedUnimplementedDevnetServiceServer()
}

func RegisterDevnetServiceServer(s grpc.ServiceRegistrar, srv DevnetServiceServer) {
	// If the following call panics, it indicates UnimplementedDevnetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DevnetService_ServiceDesc, srv)
}

func _DevnetService_CreateDevnet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDevnetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevnetServiceServer).CreateDevnet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevnetService_CreateDevnet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevnetServiceServer).CreateDevnet(ctx, req.(*CreateDevnetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevnetService_GetDevnet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDevnetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevnetServiceServer).GetDevnet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevnetService_GetDevnet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevnetServiceServer).GetDevnet(ctx, req.(*GetDevnetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevnetService_ListDevnets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevnetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevnetServiceServer).ListDevnets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevnetService_ListDevnets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevnetServiceServer).ListDevnets(ctx, req.(*ListDevnetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevnetService_DeleteDevnet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDevnetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevnetServiceServer).DeleteDevnet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevnetService_DeleteDevnet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevnetServiceServer).DeleteDevnet(ctx, req.(*DeleteDevnetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevnetService_StartDevnet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDevnetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevnetServiceServer).StartDevnet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevnetService_StartDevnet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevnetServiceServer).StartDevnet(ctx, req.(*StartDevnetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevnetService_StopDevnet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopDevnetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevnetServiceServer).StopDevnet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevnetService_StopDevnet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevnetServiceServer).StopDevnet(ctx, req.(*StopDevnetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DevnetService_ServiceDesc is the grpc.ServiceDesc for DevnetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DevnetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devnetd.v1.DevnetService",
	HandlerType: (*DevnetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDevnet",
			Handler:    _DevnetService_CreateDevnet_Handler,
		},
		{
			MethodName: "GetDevnet",
			Handler:    _DevnetService_GetDevnet_Handler,
		},
		{
			MethodName: "ListDevnets",
			Handler:    _DevnetService_ListDevnets_Handler,
		},
		{
			MethodName: "DeleteDevnet",
			Handler:    _DevnetService_DeleteDevnet_Handler,
		},
		{
			MethodName: "StartDevnet",
			Handler:    _DevnetService_StartDevnet_Handler,
		},
		{
			MethodName: "StopDevnet",
			Handler:    _DevnetService_StopDevnet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "devnet.proto",
}
