// api/proto/v1/devnet.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: devnet.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Devnet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *DevnetMetadata        `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *DevnetSpec            `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *DevnetStatus          `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Devnet) Reset() {
	*x = Devnet{}
	mi := &file_devnet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Devnet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Devnet) ProtoMessage() {}

func (x *Devnet) ProtoReflect() protoreflect.Message {
	mi := &file_devnet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Devnet.ProtoReflect.Descriptor instead.
func (*Devnet) Descriptor() ([]byte, []int) {
	return file_devnet_proto_rawDescGZIP(), []int{0}
}

func (x *Devnet) GetMetadata() *DevnetMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Devnet) GetSpec() *DevnetSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Devnet) GetStatus() *DevnetStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type DevnetMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Generation    int64                  `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations   map[string]string      `protobuf:"bytes,6,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DevnetMetadata) Reset() {
	*x = DevnetMetadata{}
	mi := &file_devnet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevnetMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevnetMetadata) ProtoMessage() {}

func (x *DevnetMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_devnet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevnetMetadata.ProtoReflect.Descriptor instead.
func (*DevnetMetadata) Descriptor() ([]byte, []int) {
	return file_devnet_proto_rawDescGZIP(), []int{1}
}

func (x *DevnetMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DevnetMetadata) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *DevnetMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DevnetMetadata) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *DevnetMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *DevnetMetadata) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type DevnetSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        string                 `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	NetworkType   string                 `protobuf:"bytes,2,opt,name=network_type,json=networkType,proto3" json:"network_type,omitempty"`
	Validators    int32                  `protobuf:"varint,3,opt,name=validators,proto3" json:"validators,omitempty"`
	FullNodes     int32                  `protobuf:"varint,4,opt,name=full_nodes,json=fullNodes,proto3" json:"full_nodes,omitempty"`
	Mode          string                 `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`
	SdkVersion    string                 `protobuf:"bytes,6,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	GenesisPath   string                 `protobuf:"bytes,7,opt,name=genesis_path,json=genesisPath,proto3" json:"genesis_path,omitempty"`
	SnapshotUrl   string                 `protobuf:"bytes,8,opt,name=snapshot_url,json=snapshotUrl,proto3" json:"snapshot_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DevnetSpec) Reset() {
	*x = DevnetSpec{}
	mi := &file_devnet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevnetSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevnetSpec) ProtoMessage() {}

func (x *DevnetSpec) ProtoReflect() protoreflect.Message {
	mi := &file_devnet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevnetSpec.ProtoReflect.Descriptor instead.
func (*DevnetSpec) Descriptor() ([]byte, []int) {
	return file_devnet_proto_rawDescGZIP(), []int{2}
}

func (x *DevnetSpec) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *DevnetSpec) GetNetworkType() string {
	if x != nil {
		return x.NetworkType
	}
	return ""
}

func (x *DevnetSpec) GetValidators() int32 {
	if x != nil {
		return x.Validators
	}
	return 0
}

func (x *DevnetSpec) GetFullNodes() int32 {
	if x != nil {
		return x.FullNodes
	}
	return 0
}

func (x *DevnetSpec) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *DevnetSpec) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *DevnetSpec) GetGenesisPath() string {
	if x != nil {
		return x.GenesisPath
	}
	return ""
}

func (x *DevnetSpec) GetSnapshotUrl() string {
	if x != nil {
		return x.SnapshotUrl
	}
	return ""
}

type DevnetStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Phase           string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	Nodes           int32                  `protobuf:"varint,2,opt,name=nodes,proto3" json:"nodes,omitempty"`
	ReadyNodes      int32                  `protobuf:"varint,3,opt,name=ready_nodes,json=readyNodes,proto3" json:"ready_nodes,omitempty"`
	CurrentHeight   int64                  `protobuf:"varint,4,opt,name=current_height,json=currentHeight,proto3" json:"current_height,omitempty"`
	SdkVersion      string                 `protobuf:"bytes,5,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	LastHealthCheck *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_health_check,json=lastHealthCheck,proto3" json:"last_health_check,omitempty"`
	Message         string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DevnetStatus) Reset() {
	*x = DevnetStatus{}
	mi := &file_devnet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevnetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevnetStatus) ProtoMessage() {}

func (x *DevnetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_devnet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevnetStatus.ProtoReflect.Descriptor instead.
func (*DevnetStatus) Descriptor() ([]byte, []int) {
	return file_devnet_proto_rawDescGZIP(), []int{3}
}

func (x *DevnetStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *DevnetStatus) GetNodes() int32 {
	if x != nil {
		return x.Nodes
	}
	return 0
}

func (x *DevnetStatus) GetReadyNodes() int32 {
	if x != nil {
		return x.ReadyNodes
	}
	return 0
}

func (x *DevnetStatus) GetCurrentHeight() int64 {
	if x != nil {
		return x.CurrentHeight
	}
	return 0
}

func (x *DevnetStatus) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *DevnetStatus) GetLastHealthCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHealthCheck
	}
	return nil
}

func (x *DevnetStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateDevnetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Spec          *DevnetSpec            `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDevnetRequest) Reset() {
	*x = CreateDevnetRequest{}
	mi := &file_devnet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDevnetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDevnetRequest) ProtoMessage() {}

func (x *CreateDevnetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devnet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDevnetRequest.ProtoReflect.Descriptor instead.
func (*CreateDevnetRequest) Descriptor() ([]byte, []int) {
	return file_devnet_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDevnetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDevnetRequest) GetSpec() *DevnetSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *CreateDevnetRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type GetDevnetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDevnetRequest) Reset() {
	*x = GetDevnetRequest{}
	mi := &file_devnet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevnetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevnetRequest) ProtoMessage() {}

func (x *GetDevnetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devnet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevnetRequest.ProtoReflect.Descriptor instead.
func (*GetDevnetRequest) Descriptor() ([]byte, []int) {
	return file_devnet_proto_rawDescGZIP(), []int{5}
}

func (x *GetDevnetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListDevnetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LabelSelector map[string]string      `protobuf:"bytes,1,rep,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevnetsRequest) Reset() {
	*x = ListDevnetsRequest{}
	mi := &file_devnet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevnetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevnetsRequest) ProtoMessage() {}

func (x *ListDevnetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devnet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevnetsRequest.ProtoReflect.Descriptor instead.
func (*ListDevnetsRequest) Descriptor() ([]byte, []int) {
	return file_devnet_proto_rawDescGZIP(), []int{6}
}

func (x *ListDevnetsRequest) GetLabelSelector() map[string]string {
	if x != nil {
		return x.LabelSelector
	}
	return nil
}

type ListDevnetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devnets       []*Devnet              `protobuf:"bytes,1,rep,name=devnets,proto3" json:"devnets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevnetsResponse) Reset() {
	*x = ListDevnetsResponse{}
	mi := &file_devnet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevnetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevnetsResponse) ProtoMessage() {}

func (x *ListDevnetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devnet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevnetsResponse.ProtoReflect.Descriptor instead.
func (*ListDevnetsResponse) Descriptor() ([]byte, []int) {
	return file_devnet_proto_rawDescGZIP(), []int{7}
}

func (x *ListDevnetsResponse) GetDevnets() []*Devnet {
	if x != nil {
		return x.Devnets
	}
	return nil
}

type DeleteDevnetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDevnetRequest) Reset() {
	*x = DeleteDevnetRequest{}
	mi := &file_devnet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDevnetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDevnetRequest) ProtoMessage() {}

func (x *DeleteDevnetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devnet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDevnetRequest.ProtoReflect.Descriptor instead.
func (*DeleteDevnetRequest) Descriptor() ([]byte, []int) {
	return file_devnet_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteDevnetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteDevnetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDevnetResponse) Reset() {
	*x = DeleteDevnetResponse{}
	mi := &file_devnet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDevnetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDevnetResponse) ProtoMessage() {}

func (x *DeleteDevnetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devnet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDevnetResponse.ProtoReflect.Descriptor instead.
func (*DeleteDevnetResponse) Descriptor() ([]byte, []int) {
	return file_devnet_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteDevnetResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type StartDevnetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDevnetRequest) Reset() {
	*x = StartDevnetRequest{}
	mi := &file_devnet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDevnetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDevnetRequest) ProtoMessage() {}

func (x *StartDevnetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devnet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDevnetRequest.ProtoReflect.Descriptor instead.
func (*StartDevnetRequest) Descriptor() ([]byte, []int) {
	return file_devnet_proto_rawDescGZIP(), []int{10}
}

func (x *StartDevnetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StopDevnetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopDevnetRequest) Reset() {
	*x = StopDevnetRequest{}
	mi := &file_devnet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopDevnetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopDevnetRequest) ProtoMessage() {}

func (x *StopDevnetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devnet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopDevnetRequest.ProtoReflect.Descriptor instead.
func (*StopDevnetRequest) Descriptor() ([]byte, []int) {
	return file_devnet_proto_rawDescGZIP(), []int{11}
}

func (x *StopDevnetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_devnet_proto protoreflect.FileDescriptor

const file_devnet_proto_rawDesc = "" +
	"\n" +
	"\fdevnet.proto\x12\n" +
	"devnetd.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x01\n" +
	"\x06Devnet\x126\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1a.devnetd.v1.DevnetMetadataR\bmetadata\x12*\n" +
	"\x04spec\x18\x02 \x01(\v2\x16.devnetd.v1.DevnetSpecR\x04spec\x120\n" +
	"\x06status\x18\x03 \x01(\v2\x18.devnetd.v1.DevnetStatusR\x06status\"\xc4\x03\n" +
	"\x0eDevnetMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x03R\n" +
	"generation\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\x06labels\x18\x05 \x03(\v2&.devnetd.v1.DevnetMetadata.LabelsEntryR\x06labels\x12M\n" +
	"\vannotations\x18\x06 \x03(\v2+.devnetd.v1.DevnetMetadata.AnnotationsEntryR\vannotations\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x02\n" +
	"\n" +
	"DevnetSpec\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\x12!\n" +
	"\fnetwork_type\x18\x02 \x01(\tR\vnetworkType\x12\x1e\n" +
	"\n" +
	"validators\x18\x03 \x01(\x05R\n" +
	"validators\x12\x1d\n" +
	"\n" +
	"full_nodes\x18\x04 \x01(\x05R\tfullNodes\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\tR\x04mode\x12\x1f\n" +
	"\vsdk_version\x18\x06 \x01(\tR\n" +
	"sdkVersion\x12!\n" +
	"\fgenesis_path\x18\a \x01(\tR\vgenesisPath\x12!\n" +
	"\fsnapshot_url\x18\b \x01(\tR\vsnapshotUrl\"\x85\x02\n" +
	"\fDevnetStatus\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x14\n" +
	"\x05nodes\x18\x02 \x01(\x05R\x05nodes\x12\x1f\n" +
	"\vready_nodes\x18\x03 \x01(\x05R\n" +
	"readyNodes\x12%\n" +
	"\x0ecurrent_height\x18\x04 \x01(\x03R\rcurrentHeight\x12\x1f\n" +
	"\vsdk_version\x18\x05 \x01(\tR\n" +
	"sdkVersion\x12F\n" +
	"\x11last_health_check\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastHealthCheck\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\"\xd5\x01\n" +
	"\x13CreateDevnetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x04spec\x18\x02 \x01(\v2\x16.devnetd.v1.DevnetSpecR\x04spec\x12C\n" +
	"\x06labels\x18\x03 \x03(\v2+.devnetd.v1.CreateDevnetRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"&\n" +
	"\x10GetDevnetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xb0\x01\n" +
	"\x12ListDevnetsRequest\x12X\n" +
	"\x0elabel_selector\x18\x01 \x03(\v21.devnetd.v1.ListDevnetsRequest.LabelSelectorEntryR\rlabelSelector\x1a@\n" +
	"\x12LabelSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x13ListDevnetsResponse\x12,\n" +
	"\adevnets\x18\x01 \x03(\v2\x12.devnetd.v1.DevnetR\adevnets\")\n" +
	"\x13DeleteDevnetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"0\n" +
	"\x14DeleteDevnetResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"(\n" +
	"\x12StartDevnetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"'\n" +
	"\x11StopDevnetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\xba\x03\n" +
	"\rDevnetService\x12C\n" +
	"\fCreateDevnet\x12\x1f.devnetd.v1.CreateDevnetRequest\x1a\x12.devnetd.v1.Devnet\x12=\n" +
	"\tGetDevnet\x12\x1c.devnetd.v1.GetDevnetRequest\x1a\x12.devnetd.v1.Devnet\x12N\n" +
	"\vListDevnets\x12\x1e.devnetd.v1.ListDevnetsRequest\x1a\x1f.devnetd.v1.ListDevnetsResponse\x12Q\n" +
	"\fDeleteDevnet\x12\x1f.devnetd.v1.DeleteDevnetRequest\x1a .devnetd.v1.DeleteDevnetResponse\x12A\n" +
	"\vStartDevnet\x12\x1e.devnetd.v1.StartDevnetRequest\x1a\x12.devnetd.v1.Devnet\x12?\n" +
	"\n" +
	"StopDevnet\x12\x1d.devnetd.v1.StopDevnetRequest\x1a\x12.devnetd.v1.DevnetB8Z6github.com/altuslabsxyz/devnet-builder/api/proto/v1;v1b\x06proto3"

var (
	file_devnet_proto_rawDescOnce sync.Once
	file_devnet_proto_rawDescData []byte
)

func file_devnet_proto_rawDescGZIP() []byte {
	file_devnet_proto_rawDescOnce.Do(func() {
		file_devnet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_devnet_proto_rawDesc), len(file_devnet_proto_rawDesc)))
	})
	return file_devnet_proto_rawDescData
}

var file_devnet_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_devnet_proto_goTypes = []any{
	(*Devnet)(nil),                // 0: devnetd.v1.Devnet
	(*DevnetMetadata)(nil),        // 1: devnetd.v1.DevnetMetadata
	(*DevnetSpec)(nil),            // 2: devnetd.v1.DevnetSpec
	(*DevnetStatus)(nil),          // 3: devnetd.v1.DevnetStatus
	(*CreateDevnetRequest)(nil),   // 4: devnetd.v1.CreateDevnetRequest
	(*GetDevnetRequest)(nil),      // 5: devnetd.v1.GetDevnetRequest
	(*ListDevnetsRequest)(nil),    // 6: devnetd.v1.ListDevnetsRequest
	(*ListDevnetsResponse)(nil),   // 7: devnetd.v1.ListDevnetsResponse
	(*DeleteDevnetRequest)(nil),   // 8: devnetd.v1.DeleteDevnetRequest
	(*DeleteDevnetResponse)(nil),  // 9: devnetd.v1.DeleteDevnetResponse
	(*StartDevnetRequest)(nil),    // 10: devnetd.v1.StartDevnetRequest
	(*StopDevnetRequest)(nil),     // 11: devnetd.v1.StopDevnetRequest
	nil,                           // 12: devnetd.v1.DevnetMetadata.LabelsEntry
	nil,                           // 13: devnetd.v1.DevnetMetadata.AnnotationsEntry
	nil,                           // 14: devnetd.v1.CreateDevnetRequest.LabelsEntry
	nil,                           // 15: devnetd.v1.ListDevnetsRequest.LabelSelectorEntry
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_devnet_proto_depIdxs = []int32{
	1,  // 0: devnetd.v1.Devnet.metadata:type_name -> devnetd.v1.DevnetMetadata
	2,  // 1: devnetd.v1.Devnet.spec:type_name -> devnetd.v1.DevnetSpec
	3,  // 2: devnetd.v1.Devnet.status:type_name -> devnetd.v1.DevnetStatus
	16, // 3: devnetd.v1.DevnetMetadata.created_at:type_name -> google.protobuf.Timestamp
	16, // 4: devnetd.v1.DevnetMetadata.updated_at:type_name -> google.protobuf.Timestamp
	12, // 5: devnetd.v1.DevnetMetadata.labels:type_name -> devnetd.v1.DevnetMetadata.LabelsEntry
	13, // 6: devnetd.v1.DevnetMetadata.annotations:type_name -> devnetd.v1.DevnetMetadata.AnnotationsEntry
	16, // 7: devnetd.v1.DevnetStatus.last_health_check:type_name -> google.protobuf.Timestamp
	2,  // 8: devnetd.v1.CreateDevnetRequest.spec:type_name -> devnetd.v1.DevnetSpec
	14, // 9: devnetd.v1.CreateDevnetRequest.labels:type_name -> devnetd.v1.CreateDevnetRequest.LabelsEntry
	15, // 10: devnetd.v1.ListDevnetsRequest.label_selector:type_name -> devnetd.v1.ListDevnetsRequest.LabelSelectorEntry
	0,  // 11: devnetd.v1.ListDevnetsResponse.devnets:type_name -> devnetd.v1.Devnet
	4,  // 12: devnetd.v1.DevnetService.CreateDevnet:input_type -> devnetd.v1.CreateDevnetRequest
	5,  // 13: devnetd.v1.DevnetService.GetDevnet:input_type -> devnetd.v1.GetDevnetRequest
	6,  // 14: devnetd.v1.DevnetService.ListDevnets:input_type -> devnetd.v1.ListDevnetsRequest
	8,  // 15: devnetd.v1.DevnetService.DeleteDevnet:input_type -> devnetd.v1.DeleteDevnetRequest
	10, // 16: devnetd.v1.DevnetService.StartDevnet:input_type -> devnetd.v1.StartDevnetRequest
	11, // 17: devnetd.v1.DevnetService.StopDevnet:input_type -> devnetd.v1.StopDevnetRequest
	0,  // 18: devnetd.v1.DevnetService.CreateDevnet:output_type -> devnetd.v1.Devnet
	0,  // 19: devnetd.v1.DevnetService.GetDevnet:output_type -> devnetd.v1.Devnet
	7,  // 20: devnetd.v1.DevnetService.ListDevnets:output_type -> devnetd.v1.ListDevnetsResponse
	9,  // 21: devnetd.v1.DevnetService.DeleteDevnet:output_type -> devnetd.v1.DeleteDevnetResponse
	0,  // 22: devnetd.v1.DevnetService.StartDevnet:output_type -> devnetd.v1.Devnet
	0,  // 23: devnetd.v1.DevnetService.StopDevnet:output_type -> devnetd.v1.Devnet
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_devnet_proto_init() }
func file_devnet_proto_init() {
	if File_devnet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_devnet_proto_rawDesc), len(file_devnet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_devnet_proto_goTypes,
		DependencyIndexes: file_devnet_proto_depIdxs,
		MessageInfos:      file_devnet_proto_msgTypes,
	}.Build()
	File_devnet_proto = out.File
	file_devnet_proto_goTypes = nil
	file_devnet_proto_depIdxs = nil
}
