// cmd/devnetd/config_init.go
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/altuslabsxyz/devnet-builder/internal/daemon/config"
	"github.com/spf13/cobra"
)

func newConfigInitCmd() *cobra.Command {
	var force bool

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Initialize devnetd configuration file",
		Long: `Creates a default devnetd.toml configuration file.

The configuration file is created at ~/.devnet-builder/devnetd.toml
with sensible defaults. You can then edit this file to customize
devnetd behavior.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			dataDir := config.DefaultDataDir()
			configPath := filepath.Join(dataDir, config.ConfigFileName)

			// Check if file exists
			if _, err := os.Stat(configPath); err == nil && !force {
				return fmt.Errorf("config file already exists: %s\nUse --force to overwrite", configPath)
			}

			// Ensure directory exists
			if err := os.MkdirAll(dataDir, 0755); err != nil {
				return fmt.Errorf("failed to create directory: %w", err)
			}

			// Generate default config content
			content := generateDefaultConfigTOML()

			// Write file
			if err := os.WriteFile(configPath, []byte(content), 0644); err != nil {
				return fmt.Errorf("failed to write config file: %w", err)
			}

			fmt.Printf("Created config file: %s\n", configPath)
			return nil
		},
	}

	cmd.Flags().BoolVarP(&force, "force", "f", false, "Overwrite existing config file")

	return cmd
}

// generateDefaultConfigTOML generates the default config file content.
func generateDefaultConfigTOML() string {
	cfg := config.DefaultConfig()
	return fmt.Sprintf(`# devnetd configuration file
# Generated by: devnetd config init
#
# Priority: defaults < this file < environment variables < CLI flags
# Environment variables use DEVNETD_ prefix (e.g., DEVNETD_LOG_LEVEL)

[server]
# Unix socket path for gRPC communication
socket = %q

# Data directory for state, logs, and plugins
data_dir = %q

# Log level: debug, info, warn, error
log_level = %q

# Number of workers per controller
workers = %d

# Run in foreground (vs daemonize)
foreground = %v

[docker]
# Enable Docker container runtime for nodes
enabled = %v

# Default Docker image for nodes
image = %q

[github]
# GitHub API token for higher rate limits and private repos
# Can also be set via DEVNETD_GITHUB_TOKEN environment variable
token = ""

[timeouts]
# Graceful shutdown timeout
shutdown = %q

# RPC health check timeout
health_check = %q

# Maximum time for snapshot downloads
snapshot_download = %q

[snapshot]
# How long to cache downloaded snapshots
cache_ttl = %q

# Maximum download retry attempts
max_retries = %d

# Delay between retries
retry_delay = %q

[network]
# Port spacing between nodes (node 0: base, node 1: base + offset, etc.)
port_offset = %d

# Base port numbers for Cosmos SDK nodes
base_rpc_port = %d   # CometBFT RPC
base_p2p_port = %d   # P2P communication
base_rest_port = %d  # REST API
base_grpc_port = %d  # gRPC API
`,
		cfg.Server.Socket,
		cfg.Server.DataDir,
		cfg.Server.LogLevel,
		cfg.Server.Workers,
		cfg.Server.Foreground,
		cfg.Docker.Enabled,
		cfg.Docker.Image,
		cfg.Timeouts.Shutdown,
		cfg.Timeouts.HealthCheck,
		cfg.Timeouts.SnapshotDownload,
		cfg.Snapshot.CacheTTL,
		cfg.Snapshot.MaxRetries,
		cfg.Snapshot.RetryDelay,
		cfg.Network.PortOffset,
		cfg.Network.BaseRPCPort,
		cfg.Network.BaseP2PPort,
		cfg.Network.BaseRESTPort,
		cfg.Network.BaseGRPCPort,
	)
}
